services:
  battleships-db:
    container_name: battleships-db
    image: postgres:16-alpine
    ports:
      - "25432:5432"
    volumes:
      - battleships-db:/var/lib/postgresql/data
    environment:
      - "POSTGRES_USER=battleships-user"
      - "POSTGRES_PASSWORD=battleships-password"
      - "POSTGRES_DB=battleships-db"
    networks:
      - battleships-network

volumes:
  battleships-db:
    driver: local

networks:
  battleships-network:
    driver: bridge
