services:
  battleships-db:
    container_name: battleships-db
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    volumes:
      - battleships-db:/var/lib/postgresql/data
    environment:
      - "POSTGRES_USER=battleships-user"
      - "POSTGRES_PASSWORD=battleships-password"
      - "POSTGRES_DB=battleships-db"
    networks:
      - battleships-network
  battleships-api:
    container_name: battleships-api
    build: .
    depends_on:
      - battleships-db
    ports:
      - "8080:8080"
    networks:
      - battleships-network
    environment:
      - "DB_HOST=battleships-db"
      - "DB_PORT=5432"
      - "DB_NAME=battleships-db"
      - "DB_USER=battleships-user"
      - "DB_PASS=battleships-password"
      - "DB_PARAMS="
  battleships-ui:
    container_name: battleships-ui
    build:
      context: ui
      args:
        - "VITE_API_URL=http://localhost:80/api"
    depends_on:
      - battleships-api
    ports:
      - "80:3000"
    networks:
      - battleships-network

volumes:
  battleships-db:
    driver: local

networks:
  battleships-network:
    driver: bridge
