axon:
  axonserver:
    enabled: false
  serializer:
    general: jackson

logging:
  level:
    dev.akif: DEBUG
    root: INFO

server:
  error:
    include-stacktrace: never

spring:
  application:
    name: getting-your-axe-on
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:25432}/${DB_NAME:battleships-db}?${DB_PARAMS:}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:battleships-user}
    password: ${DB_PASSWORD:battleships-password}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
  threads:
    virtual:
      enabled: true
