axon:
  axonserver:
    enabled: false
  serializer:
    general: jackson

logging:
  level:
    dev.akif: DEBUG
    org.axonframework: DEBUG
    org.springframework: INFO
    web: INFO

server:
  error:
    include-stacktrace: never

spring:
  application:
    name: getting-your-axe-on
  datasource:
    url: jdbc:postgresql://localhost:5432/counters-db
    driver-class-name: org.postgresql.Driver
    username: counters-user
    password: counters-password
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  threads:
    virtual:
      enabled: true
